services:
  stockr-db:
    image: postgres:15-alpine
    container_name: stockr-postgres-db
    environment:
      POSTGRES_DB: stockr
      POSTGRES_USER: stockr
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockr -d stockr"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stockr-app:
    build: .
    container_name: stockr-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.5432/stockr?currentSchema=stockr_dev
      SPRING_DATASOURCE_USERNAME: stockr
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - stockr-db
volumes:
  postgres_data: