spring:
  application:
    name: stockr
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stockr}
    username: ${SPRING_DATASOURCE_USERNAME:stockr}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  messages:
    basename: messages
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
  type-aliases-package: net.naoponju.stockr.domain.entity
logging:
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}-%i.gz"
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false
  pattern:
    console: "%d{yyyy-MM-dd HH:mm.ss} %-5level [%thread] %logger{36} : %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    net.naoponju.stockr: DEBUG
server:
  port: 8080